# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dcb0ac948bddeea120fd1b4f7fafbc205eaaaeb902d537fb7a452e8b2b3f7112db7fe877888d9ff4b2da153514bd2bdd1227dd62f44e7c76fc7ba565a08d5d9

test:
  secret_key_base: 128d3a20f491720b8972cccbcb32edf6614d77546bbcb96bbdea292e2c38aa2c5b4e011ec3df7ad2ee4892eaa420f0118e12f48433cd0105f8c7264472e459a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
